### ISSUE TITLE
Multi-line messages from IRC arrive out-of-order in web interface

### ISSUE THREAD

**Issue by lucaswerkmeister** [gitterHQ/irc-bridge#23]
I sent the following message from IRC:

![screenshot from 2015-05-13 02-53-58](https://cloud.githubusercontent.com/assets/2346599/7601793/922d5b94-f91b-11e4-9935-07a5de60cd6f.png)

As you can see by the timestamp, I wrote a multi-line message in one go (using Shift+Return), which my client (Pidgin) then sent in immediate succession as multiple chats.

This is how it looks on the website:

![screenshot from 2015-05-13 02-54-18](https://cloud.githubusercontent.com/assets/2346599/7601811/c7810ac0-f91b-11e4-9a8f-9d0c9c39599b.png)

I understand that multi-line Markdown (code blocks) doesn’t work in such a message… but it’s very weird and confusing that the messages arrived out of order. I’ve never had problems with this kind of multi-line message on Freenode, so I don’t think it’s a restriction of IRC.

**Comment by malditogeek** [comment]
I think the order should be easy to fix. My guess is that they are in the wrong order because behind the scene the bridge is posting them over HTTP to our API in parallel so there might be race conditions there if you send a bunch of messages simultaneously.

About the multi-line messages, IRC can't handle line breaks because CR LF is part of the protocol and is used as a separator https://tools.ietf.org/html/rfc1459#section-2.3.1 so when you send a multi-line markdown block we'll get each line as a message and we can't parse that unfortunately. They'll just be displayed as individual messages.

How does Freenode handle this? can you post a screenshot please?

**Comment by lucaswerkmeister** [comment]
> How does Freenode handle this?

There’s no special handling, I just meant that they arrive in the right order. My client still shows them as separate messages (with the same timestamp, except when the messages are throttled).
