### ISSUE TITLE
Apply bold / italics IRC stylings instead of sending raw markdown

### ISSUE THREAD

**Issue by ThePsionic** [gitterHQ/irc-bridge#47]
It's possible to insert characters that color and style code. As such, `*thing*` should be rendered as *thing*, `**thing**` should be rendered as **thing**, and `***thing***` should be rendered as ***thing***.

**Comment by lucaswerkmeister** [comment]
No. Aw hell no. Oh god, *please*, no! I hate the sound of that, and after a quick Google, I am *appalled* to find out what horrible hacks clients have added to the **plain text protocol** IRC because someone wants to look cool and add fancy colors.

Please, Gitter devs… no.

---

A more practical concern: Markdown is sometimes difficult to get right (pop quiz: how do you produce _\*cough\* [something] \*cough\*_? trick question; it depends on your implementation of course, because there is no such thing as a [standard Markdown](http://commonmark.org/)), and seeing the plain source in the IRC bridge frequently allows us to help users who can’t get their formatting to work (“you need to add a newline between the ```` ``` ```` and the actual code”). For this, it is important that we can see the pure, plain, unaltered Markdown source.

**Comment by trevorah** [comment]
I'm with @lucaswerkmeister on this one. Markdown is meant to be readable as source and uses the existing plaintext conventions to imply emphasis. Markdown rendering is up to the client.
