### ISSUE TITLE
Auto-join channels on successful connect

### ISSUE THREAD

**Issue by Unode** [gitterHQ/irc-bridge#62]
Given the list of channels one has joined via the gitter.im interface, would it be possible to automatically join all of them when connecting via the IRC bridge?

The intention is to have the IRC client behave more like the gitter.im interface where all the channels are automatically displayed. Otherwise one needs to memorize the channel name or configure the IRC client to explicitly join a set of channels.

**Comment by lucaswerkmeister** [comment]
Is this even possible? Can the server make the client join some channels?

**Comment by Unode** [comment]
I'd say so. At least I remember clearly on some servers getting a forceful join to `#guests` if you fail to authenticate in due time.

**Comment by Unode** [comment]
[This hints](http://www.geekshed.net/commands/ircop/#SAJOIN) that is is indeed possible.

From what I could gather, the server sends a JOIN to the client. Most clients treat the JOIN as if it was requested in the first place and behave normally.

There might be cases where the client doesn't comply but this will become client specific and mostly harmless.

**Comment by Gargaj** [comment]
It's entirely possible, the joining of a channel is an incoming server response that can come without an outgoing client request in front of it.

**Comment by lucaswerkmeister** [comment]
Oh god, it looks like this change was just deployed, and I was just joined to a dozen lucaswerkmeister/something test channels. So now that I’ve experienced what this change does… I’m sorry, but I **hate** it. My client is already set up to auto-join the channels that I actually care about (I’m pretty sure most clients support something like this). I do **not** need the server to guess at which channels I want to be in. Please, at the very least, add a way to disable this.

**Comment by Unode** [comment]
No complains on my part. Works as requested.
Although I see that making it configurable wouldn't hut.

**Comment by MadLittleMods** [comment]
@lucaswerkmeister This is aimed especially at new users just coming to IRC and wanting to sync what they have on Gitter or not knowing what to enter for a channel name or how to determine it.

It should be joining the 10 rooms you last accessed.

Is there a good way to detect whether you already have rooms and only run if you don't have any?

**Comment by lucaswerkmeister** [comment]
Ten rooms seems excessive to me. Is that a usual number of rooms to be in? I regularly use three.

And I don’t understand why you’re including features aimed at users new to IRC – why would those people use the IRC bridge in the first place? I thought the IRC bridge was for people who already use to IRC and want to keep using it… if you’re new to IRC, just stick with the web version (and enjoy the Markdown support, editing support, etc.).

**Comment by MadLittleMods** [comment]
@lucaswerkmeister I meant users who are using Gitter, discover the IRC Bridge, and start using it. New users to the IRC Bridge I guess describes it better.

**Comment by Gargaj** [comment]
If you don't regularly use rooms, don't be in those rooms. The purpose of an IRC bridge is to mirror exactly the events on the site.

That being said, it might be a reasonable idea to not auto-join rooms that haven't had any activity for a week or so.

**Comment by lucaswerkmeister** [comment]
> The purpose of an IRC bridge is to mirror exactly the events on the site.

This is what happens to my Pidgin with this feature:

![screenshot from 2016-06-14 18-30-33](https://cloud.githubusercontent.com/assets/2346599/16051001/23ab6ba2-325e-11e6-9b6b-368573835ce0.png)

It joined me to so many rooms, they don’t even fit on the screen anymore!

If the IRC bridge really mirrored the website version, then the website version would open ten browser tabs each time I opened it. I hope we can all agree that would be extremely annoying.

> If you don't regularly use rooms, don't be in those rooms.

Why? On the web version, there’s no drawback to being in many rooms. I view the room list as a list of rooms I care about *some* of the time, not necessarily *all* of the time. When I want to participate in the discussion, I quickly move to the room via the sidebar; otherwise, I don’t need to care about it, since the website kindly hides it from me.

In fact, the recent UI update seems to reinforce that view, in my opinion. Since rooms are grouped by organization, there’s even more space for rooms to be in, and since the sidebar is collapsed by default, the size of the room list has no influence at all on normal usage as long as you’re staying in one room.

> That being said, it might be a reasonable idea to not auto-join rooms that haven't had any activity for a week or so.

This doesn’t solve the problem that my IRC client is already configured to auto-join the rooms I actually care about, and this feature now leaves me with two copies of that room, which Pidgin doesn’t handle well.

I’d like to reiterate my point: this is a feature that almost all clients already implement, and the server implementation is worse than those client implementations because it can only guess at which rooms the client actually wants to join. It’s simply not the right place to do this.

**Comment by Unode** [comment]
> If the IRC bridge really mirrored the website version, then the website version would open ten browser tabs each time I opened it. I hope we can all agree that would be extremely annoying.

This comparison is a little over the top. The browser implements rooms in a rather different way all the information is there at the distance of a click. You can't really do the same over IRC.

> Why? On the web version, there’s no drawback to being in many rooms.

Again, different technologies and limitations.

> This doesn’t solve the problem that my IRC client is already configured to auto-join the rooms I actually care about, and this feature now leaves me with two copies of that room, which Pidgin doesn’t handle well.

I'd say the duplication of channels deserves a bug report to Pidgin. I use Weechat and have not noticed any problems like that. I imagine that with server restarts the channels would just keep growing instead of reusing existing tabs.

Additional channels aren't really a problem either as tabs are not shown the same way on Weechat. Call it a UI limitation in the Pidgin case. Still consider that this is not specific to Gitter since the same usability problem is present if you want to be in many channels or many IRC servers.

I agree with providing a way to disable this feature if desired but other than that I'd say the implementation is fair.

In any case, I see the IRC bridge as a convenience over the web interface and not really as a main feature of Gitter. There's only so many things one can bridge over.

From my part I consider the original request implemented and therefore closed.

**Comment by belak** [comment]
> Ten rooms seems excessive to me.

In all honesty, for me it would be nice to join all of the rooms I've joined in the web UI... but that may just be me.

Perhaps there could be a delay in joining on the bridge side? Then if you haven't joined any rooms by then, it would auto-join you to your latest rooms. It seems like this would fix most problems... people who use auto-join in the client would be able to keep using auto-join, it wouldn't make you join all your rooms if you don't want to, and for users who aren't sure what's going on, it should still join them.

The one downside is that if your client sets up auto-joins as you join rooms, this could get out of sync with the web UI... which can end up being a pain.

**Comment by lucaswerkmeister** [comment]
> Again, different technologies and limitations.

Exactly – but joined now by this feature. Being in lots of rooms is fine on the web, cumbersome on the IRC bridge. This feature now forces me to leave those rooms on the web as well.

> Still consider that this is not specific to Gitter since the same usability problem is present if you want to be in many channels or many IRC servers.

Yes, but I **don’t** “want” to be in many rooms in this case. The IRC bridge is **forcing** this on me.

> There's only so many things one can bridge over.

So why bridge this, when it has so many problems? “Ten last accessed rooms” is a **completely arbitrary guess** – it might just as well be five rooms, or twenty, or all of them. And they might also be ordered by the room’s activity, or by join time, or by size. The server **cannot** know which channels I’m actually interested in, which is why this feature belongs on the **client**, where I can configure it at my leisure.

> I agree with providing a way to disable this feature if desired but other than that I'd say the implementation is fair. […]
> From my part I consider the original request implemented and therefore closed.

I’m not arguing that the implementation is shoddy or anything. I’m arguing (perhaps a bit late) that this is a bad feature to implement in the first place.

----

I don’t want to sound too much like a nagger here… am I really, truly, the only person bothered by this? If yes, fine, I’ll just run my own fork :-( but I find that hard to believe – for one, because Pidgin is (for better or worse) the default IRC client on many Linux distributions, and so any UI limitations or bugs it has, whatever you call them, are presumably fairly widespread.

**Comment by belak** [comment]
> Pidgin is (for better or worse) the default IRC client on many Linux distributions

Yes, pidgin *can* work, but it's really designed as a 1-1 IM app... the group chat features are there but fall really flat in situations with a large number of rooms or people.

XChat and Hexchat have been fairly popular IRC clients for a long time... there's also KIRC (for KDE users) and smuxi (a newcomer, but (I think) the official gnome client).

My previous suggestion (the delay for joining rooms) seems like it would fix the 99% case... would that be reasonable? Right now this is complicated by the fact that the IRC protocol doesn't have a great way of asking to not be auto-joined... so it would need to be a non standard extension of some point.

**Comment by MadLittleMods** [comment]
> Is there a good way to detect whether you already have rooms and only run if you don't have any? What are some good ways to tackle disabling (commands on connect configured via IRC client, etc)?
> https://github.com/gitterHQ/irc-bridge/issues/62#issuecomment-225632375

As I stated earlier, let's find a good way to disable the functionality for those who don't want to use it.

Adding a delay(perhaps 3 seconds) then only auto-join if we see that no join room commands were sent seems like the best suggestion so far that @belak mentioned and I was hinting at. The magic delay time for this is ever-so-slightly questionable. Feel free to start a PR.

---

The duplicate room issue sounds like a Pidgin bug. When testing IRCCloud or HexChat, I didn't see any issues.

**Comment by lucaswerkmeister** [comment]
> Adding a delay(perhaps 3 seconds) then only auto-join if we see that no join room commands were sent seems like the best suggestion so far that @belak mentioned and I was hinting at.

Oh, I think I misunderstood this suggestion earlier. If the server skips *all* joins if the client sent *any* already, that would solve my problem completely. (I thought the suggestion was just to skip joining those rooms that the client already joined.)

**Comment by dequis** [comment]
The pidgin issue seems to be a problem with both sides. While pidgin should handle repeated JOINs from the server, the gitter server shouldn't be sending those at all. Both sides should ignore repeated JOINs. #66 does that.

**Comment by pdurbin** [comment]
I configure my IRC client (Weechat) to automatically join certain channels/rooms on Gitter on startup. Now I'm being sucked into channels I haven't participated in for months, up to 10 of them, from what I gather by reading through this issue.

Please provide a way to disable the new feature that was apparently implemented in pull request #63 ("Enable auto-join-on-connect") so that I can regain control of which channels I join when I connect to the Gitter IRC bridge. I'm happier having this control in my IRC client than having it forced upon me by the Gitter server.

Thanks for providing such a fantastic service!

**Comment by MadLittleMods** [comment]
@lucaswerkmeister @pdurbin I created a PR to autojoin 1 second after connecting only if you haven't joined other rooms (via your client's autojoin feature, etc). I would appreciate any review or testing, https://github.com/gitterHQ/irc-bridge/pull/68

**Comment by dequis** [comment]
How about using the password field to pass extra server settings? Something like `d41d8cd98f00b204e9800998ecf8427e,autojoin=0`. This can be mentioned in the irc.gitter.im website. I think it's a decent place to put this kind of stuff, given how the bridge has to be stateless.

**Comment by MadLittleMods** [comment]
@dequis Is there any precedent for this?

The solution to not autojoin if we have seen any joins within a time-frame is pretty seamless. I don't fully understand the [issue you mentioned about it](https://github.com/gitterHQ/irc-bridge/pull/68#issuecomment-226400422).

What about a command to run on connect that many IRC clients have? Is this any better?

**Comment by dequis** [comment]
@MadLittleMods I asked around, looks like slack's irc gateway allows adding `-voice` to the IRC server password to remove the voicing/devoicing when someone goes AFK. ([mentioned at the end of this page](https://get.slack.help/hc/en-us/articles/201727913-Connecting-to-Slack-over-IRC-and-XMPP))

A command to run on connect to opt-in to autojoining channels sounds good too. IMO it's less straightforward than using a field that users already have to deal with.

**Comment by belak** [comment]
Arguably, znc does something similar to this as well. When you connect, you put username/network:password in the password field to specify which user and network to connect to.

**Comment by MadLittleMods** [comment]
v1.2.0 is out in production so you shouldn't be running into server autojoining if you are already using client autojoin anymore.

cc @lucaswerkmeister @pdurbin

**Comment by lucaswerkmeister** [comment]
It works! Thanks.
